### PR TITLE
Added the option to change the name of the identification attribute

### PR DESCRIPTION
**Pull request by Globegitter**
Our backend requires the identification attribute to be `email` rather than username, so I added the option to change that.
Let me know if all is looking good.

### CODE REVIEW

**Comment by jpadilla** [comment]
@Globegitter looks great, left a comment to fix some styling issues.

**Comment by Globegitter** [comment]
@jpadilla More than happy to make the changes - how can I test against the jshint issues? Or is it just the change you mentioned?
Made the other change you mentioned.

**Comment by jpadilla** [comment]
@Globegitter sorry, no tests yet :( I've added a `.jshintrc` so I've you've got jshint installed it should pick that up. I use that together with SublimeLlinter-jshint on ST3.

**Comment by jpadilla** [comment]
@Globegitter added a Gruntfile with some linting tasks. You can do `grunt lint`

**Comment by Globegitter** [comment]
Thank you for that - just installed the ST3 plugin, but the grunt task was a bit quicker. Should I send a new PR with squashed commits, or is that fine?

**Comment by jpadilla** [comment]
@Globegitter Thanks again! Just released v0.2.0

**Comment by Globegitter** [comment]
@jpadilla Thank you - appreciated

**Pull request merged**
