### PR TITLE
Add support for custom headers

### PR DESCRIPTION
**Pull request by leandrocp**
Add an optional customHeader configuration, wich will send custom headers on every authentication request.

Just like http://emberjs.com/api/data/classes/DS.RESTAdapter.html#toc_headers-customization

### CODE REVIEW

**Comment by jpadilla** [comment]
@leandrocp looks good to me. How about calling it `headers` instead of `customHeader` just like how it's done in `DS.RESTAdapter`?

**Comment by leandrocp** [comment]
@jpadilla that´s fine to me. I´ll update the pull request.

**Comment by leandrocp** [comment]
@jpadilla done!

**Comment by jpadilla** [comment]
@leandrocp Thanks!

**Pull request merged**
