### PR TITLE
chore(deps): allow ember-simple-auth ^1.6.0 || ^2.1.0

### PR DESCRIPTION
**Pull request by scottkidder**
and upgrade the lockfile to 2.1.0

### CODE REVIEW

**Comment by methodmedia** [comment]
Hey @scottkidder, I also need this version bump, looks like its failing the CI build though, any chance you can look into that so this could get merged?

**Comment by mikeburg** [comment]
Any update on this pull request? What need to be fixed?

**Comment by tben** [comment]
ember-simple-auth 2.0 dropped support for node version 6. So to fix this, Travis would need to use a newer version than 6.

**Comment by fenichelar** [comment]
I have started working on this. I'm not having good success with Travis. I will circle back later.

**Pull request closed without merging**
