### PR TITLE
V2 addon, embroider compat, use pnpm, drop ember <= 4.8

### PR DESCRIPTION
**Pull request by AmauryD**
TODO:

- [ ] Remove the references to @TRIPTYK before merging
- [x] Get fastboot support back (add tests ?)

### CODE REVIEW

**Comment by spruce** [comment]
I think the initializers are no longer neccessary. 
I just added the authenticator into the authenticators folder of my app and without any initializers it got found.

**Comment by fenichelar** [comment]
@ChrisN-transnexus

**Comment by gzurbach** [comment]
This looks great! We would love to see this merged so that we can update our app to Ember 5. Thanks for working on this @AmauryD 👍

**Comment by ChrisN-transnexus** [comment]
@AmauryD I tried to install this in an Ember 5.4.1 app via `pnpm i https://github.com/AmauryD/ember-simple-auth-token.git` but ran into difficulties.

The consuming app uses `@embroider/webpack` and `@embroider/compat`, `ember-auto-import` 2.6.3, `webpack` 5.78.0 and `@embroider/addon-dev` 4.3.1, but the resulting code installed under `node_modules/workspace-root` and is referenced in package.json as `"workspace-root": "github:AmauryD/ember-simple-auth-token"`

The consuming app can't import the `ember-simple-auth-token` modules when they are under `workspace-root`. Am I doing something wrong or does the consuming app need some config changes?

**Comment by AmauryD** [comment]
> @AmauryD I tried to install this in an Ember 5.4.1 app via `pnpm i https://github.com/AmauryD/ember-simple-auth-token.git` but ran into difficulties.
> 
> The consuming app uses `@embroider/webpack` and `@embroider/compat`, `ember-auto-import` 2.6.3, `webpack` 5.78.0 and `@embroider/addon-dev` 4.3.1, but the resulting code installed under `node_modules/workspace-root` and is referenced in package.json as `"workspace-root": "github:AmauryD/ember-simple-auth-token"`
> 
> The consuming app can't import the `ember-simple-auth-token` modules when they are under `workspace-root`. Am I doing something wrong or does the consuming app need some config changes?

Hello @ChrisN-transnexus,

Installing an Ember V2 addon directly using github isn't possible due to the dist build not being published by default. I've added a CI task to solve this problem. You can install the dist build on this branch: [link](https://github.com/AmauryD/ember-simple-auth-token/tree/master-dist).

`pnpm add -D https://github.com/AmauryD/ember-simple-auth-token.git\#master-dist --ignore-scripts`

**Pull request closed without merging**
