### PR TITLE
Fixed jquery 3 promise handling to be compatible with ember promises

### PR DESCRIPTION
**Pull request by pfmmfp**
More info explained [here](http://jquery.com/upgrade-guide/3.0/\#callback-invocation), which has been found based on [this ember issue](https://github.com/emberjs/ember.js/issues/14566)

### CODE REVIEW

**Comment by jpadilla** [comment]
I'd rather us just drop replace this with `ember-network` like [ember-simple-auth](https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/devise.js#L187) is doing now.

**Comment by jeffhertzler** [comment]
any update on this? causing me some headaches. getting race conditions in my acceptance tests. using a fork with this proposed fix for now.

**Comment by morhook** [comment]
@jeffhertzler we had some issues with the migration to `ember-network`. You could use a more updated version that is also patched on my fork if you want: https://github.com/morhook/ember-simple-auth-token/commits/fix_jquery_3_ember_2_10

Sorry for not having a better fix yet.

**Comment by jeffhertzler** [comment]
No problem. Yeah, your fork is what I'm using for now. Works great til there's a more permanent solution.

**Comment by jpadilla** [comment]
@morhook would you want to give this another try? Seems like the preferred alt is `ember-fetch`. https://github.com/simplabs/ember-simple-auth/pull/1288

If not, anyone else can step up or I'll give it a go in a couple of days.

**Comment by alechirsch** [comment]
Using ember-fetch seems like the right way to go, I can review a pull request for including ember-fetch.

**Comment by knownasilya** [comment]
@alechirsch https://github.com/jpadilla/ember-simple-auth-token/pull/200 although I'm not sure how to stub fetch, and fix the tests. Any guidance is appreciated.

Maybe something like http://www.wheresrhys.co.uk/fetch-mock/ ?

**Comment by jpadilla** [comment]
Closed by #226. Thanks again everyone!

**Pull request closed without merging**
