### PR TITLE
Drop support for Node v6 and v8

### PR DESCRIPTION
**Pull request by fenichelar**

### CODE REVIEW

**Comment by fenichelar** [comment]
@jelhan and @tben Thoughts?

**Review by jelhan — DISMISSED** [review]
Looks good to me.

**Comment by tben** [comment]
Also looks good to me. Just need someone to create a tag of release 4.0.8 before we commit this one.

**Comment by fenichelar** [comment]
@tben I made the release

**Comment by fenichelar** [comment]
v5.0.0
```
# Changelog

- Drop support for Node.js v6 and v8
- Fix Travis config warnings
```

**Review by jpadilla — APPROVED** [review]

**Pull request merged**
