### PR TITLE
Fixed issue with custom identification and password fields

### LINKED ISSUE #170: identificationField can't overwrite
Trying to use `email` instead of the default `identification` with `identificationField: 'email'` but it's not working. It only works if I use `identification` in my login form. Any ideas?

### PR DESCRIPTION
**Pull request by Eusse**
Fixes #170

### CODE REVIEW

**Comment by januszm** [comment]
I'd say we have the same issue with other configuration variables, like `serverTokenEndpoint`

**Comment by januszm** [comment]
👍

**Comment by poohitan** [comment]
Any updates? I wonder why this is still not merged.

**Review by alechirsch — APPROVED** [review]

**Review by angusmckay001 — APPROVED** [review]
Can we please get this merged. Can If not can we get a comment why and close the pull request.

**Pull request merged**
