### PR TITLE
Fixes #10

### LINKED ISSUE #10: Cannot restore session after page refresh
It seems I cannot find a way to restore the session on page reload.

As soon as the session is authenticated, localStorage contains the correct data. Then if I refresh the page I get redirected to the login page and localStorage is empty.

Is this supposed to be the standard behavior?

### PR DESCRIPTION
**Pull request by rbartoli**

### CODE REVIEW

**Comment by rbartoli** [comment]
@jpadilla Sorry for the mess but this is my first pull request. I've tested this in my project and it's working correctly with different values for [tokenPropertyName](https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/app/authorizers/token.js#L53)

**Comment by jpadilla** [comment]
Hey @rbartoli, thanks for getting this together, great work! Just released as v0.3.0

**Comment by rbartoli** [comment]
@jpadilla No worries! Has this also been updated on npm? Thanks

**Comment by jpadilla** [comment]
@rbartoli oops, forgot to publish. Should be good now.

https://www.npmjs.org/package/ember-cli-simple-auth-token

**Comment by rbartoli** [comment]
@jpadilla Cool, thanks!

**Pull request merged**
