### PR TITLE
User base64 instead of atob for fastboot support

### PR DESCRIPTION
**Pull request by fenichelar**
Fixes https://github.com/jpadilla/ember-simple-auth-token/issues/247

`window.base64` from https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js#L122

### CODE REVIEW

**Comment by fenichelar** [comment]
@jpadilla Yes, but it is probably not a good idea to depend on that undocumented behavior. I will reproduce internally. Good point!

**Comment by fenichelar** [comment]
@jpadilla I think that is better.

**Comment by jpadilla** [comment]
@musaffa any chance you could test this out and see if it resolves your original issue?

**Review by jpadilla — DISMISSED** [review]

**Comment by fenichelar** [comment]
Yes, `buffer` must be added to `fastbootDependencies`. We should add some documentation about this.

------------------------------------------------

Using the `FastBoot` should be no different than `require`:

> From your Ember.js app, you can run FastBoot.require() to require a package. This is identical to the CommonJS require except it checks all requests against the whitelist first.

I'm hesitant to use the `FastBoot` global in this library.

------------------------------------------------

> A simple (atob) conditional check doesn't work.

What does it do?

------------------------------------------------

> Unable to require module 'buffer' because it was not in the whitelist

That seems like a good error message to me... however, it will not be displayed if the `FastBoot` global is not used. So custom error message makes sense.

------------------------------------------------

Update incoming.

**Comment by musaffa** [comment]
> > A simple (atob) conditional check doesn't work.
> 
> What does it do?

`(typeof atob !== 'undefined')` is the right way to check for the presence of atob. The simple check currently present in the PR doesn't work.

**Comment by musaffa** [comment]
IMHO you should test the changes in a Fastboot environment.

**Comment by fenichelar** [comment]
@musaffa I did... and it worked fine. I did add buffer to the fastbootDependencies.

**Comment by fenichelar** [comment]
```js
const decode = str => {
  if (typeof atob === 'function') {
    return atob(str);
  } else if (typeof FastBoot === 'object') {
    try {
      const buffer = FastBoot.require('buffer');
      return buffer.Buffer.from(str, 'base64').toString('utf-8');
    } catch (err) {
      throw new Error('buffer must be available for decoding base64 strings in FastBoot. Make sure to add buffer to your fastbootDependencies.');
    }
  } else {
    throw new Error('Neither atob nor the FastBoot global are avaialble. Unable to decode base64 strings.');
  }
};
```

I think that should be good.

**Comment by musaffa** [comment]
LGTM

**Comment by fenichelar** [comment]
@jpadilla Thoughts on this?

**Review by jpadilla — APPROVED** [review]

**Pull request merged**
