### PR TITLE
Improve fetch error handling, add ESA dependency, allow disabling session invalidation

### PR DESCRIPTION
**Pull request by fenichelar**
Fixes https://github.com/jpadilla/ember-simple-auth-token/issues/234
Fixes https://github.com/jpadilla/ember-simple-auth-token/issues/236
Fixes https://github.com/jpadilla/ember-simple-auth-token/issues/239

### CODE REVIEW

**Comment by fenichelar** [comment]
Version 4.0.3. Changelog:

```
# Changelog

- Improve fetch error handling #234
- Add Ember Simple Auth to dependencies #236
- Allow disabling session invalidation on token expiration #239
```

**Comment by happycollision** [comment]
I'm not entirely sure what special sauce is added to `ember install` vs `yarn add` or `npm install`, but is it possible that `ember-simple-auth` should be a *peer dependency* of ESAT?

Does changing the install instructions to simply 

```
ember install ember-simple-auth-token
```

 actually change how `ember-simple-auth` might be installed?

**Comment by fenichelar** [comment]
See the change to `package.json`, `ember-simple-auth` was a development dependency and now it is a dependency. This means `ember install ember-simple-auth-token ` (or `npm install ember-simple-auth-token` or `yarn install ember-simple-auth-token`) will install `ember-simple-auth`. Therefore the install instructions were changed. This is the same as `ember-simple-auth-auth0`: https://github.com/auth0-community/ember-simple-auth-auth0/blob/develop/package.json#L84.

**Comment by happycollision** [comment]
Right on. Like I said, I didn’t know if `ember install` worked any differently from `npm install` when it comes to dependencies.

**Review by jpadilla — COMMENTED** [review]
@fenichelar I'm wondering if we should make less assumptions on these responses...

Was checking out what ESA does in their authenticators: https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js

- They've included a `rejectWithResponse` property on the authenticator.
- https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js#L326

Thoughts?

**Comment by fenichelar** [comment]
@jpadilla Mmmm. What assumptions are you referring to? I think the result is pretty similar to oauth2. It returns JSON if possible and plain text if not.

It seems like oauth2 added `rejectWithResponse` for when you want to access the status code or status text:

> This is useful for cases when the backend provides additional context not available in the response body.

It seems simpler to just always include the status code and status text so that you don't need to override the callback. I think that is the only really difference unless I am missing something, which I totally could be?

**Comment by fenichelar** [comment]
@jpadilla What do you think we should do?

**Comment by jpadilla** [comment]
@fenichelar In that case could we include status code, status text, and response headers?

**Comment by fenichelar** [comment]
@jpadilla 

> response headers

Done! Great suggestion. The headers are in a map because that is what `fetch` does: `response.headers.get('HEADER_NAME')`.

I also made `makeRequest` return all the response data for a successful return too. This makes the API more consistent and allows someone to easily change `authenticate` to support returning the token in a header or anything else like that.

**Review by jpadilla — APPROVED** [review]

**Pull request merged**
