### PR TITLE
expiresAt restore

### PR DESCRIPTION
**Pull request by epustobaev**
dataObject property name "expiresAt" not equals token property name "exp"

### CODE REVIEW

**Comment by erichaus** [comment]
@epustobaev which version of this package are you using? The newest version has an update to the Ember.merge in question and should work.

**Comment by engwan** [comment]
This is the same problem I described in https://github.com/jpadilla/ember-cli-simple-auth-token/issues/71.

https://github.com/jpadilla/ember-cli-simple-auth-token/pull/69 should fix this issue.

**Comment by engwan** [comment]
https://github.com/jpadilla/ember-cli-simple-auth-token/pull/73 was merged, which fixes this issue

**Comment by erichaus** [comment]
this should be closed as it was fixed via #73

**Pull request closed without merging**
