### PR TITLE
added enableHttpsWarnings configuration property

### PR DESCRIPTION
**Pull request by dennismende**
While local development it would be nice, that you can disable https warnings.

That's why I added a configuration property called "enableHttpsWarnings" which defaults to false

### CODE REVIEW

**Comment by jpadilla** [comment]
@dennismende Thanks, but now that I check into it, I'd prefer to follow what was done in https://github.com/simplabs/ember-simple-auth/issues/318

**Comment by dennismende** [comment]
Are there any information about the status of such an implementation. All these warnings are really annoying.

**Comment by jpadilla** [comment]
@dennismende I'll probably release a new version which includes the changes in b9537a2064d6f1607df180781a8ef8f780e45ce6 that removes the warning.

**Comment by jpadilla** [comment]
@dennismende v0.5.0 is out https://github.com/jpadilla/ember-cli-simple-auth-token/releases/tag/v0.5.0

**Comment by dennismende** [comment]
Thanks

**Pull request closed without merging**
