### PR TITLE
Allow for strings to be used as token data

### PR DESCRIPTION
**Pull request by knownasilya**
Pretty much `JSON.parse` chokes if you give it a string (valid json).

### CODE REVIEW

**Comment by jpadilla** [comment]
@knownasilya any chance of a small test?

**Comment by knownasilya** [comment]
@jpadilla yeah let me figure out how to create a fake token with data.

**Comment by knownasilya** [comment]
@jpadilla does that look good?

**Comment by jpadilla** [comment]
Yup. Quick question, what's your use case for a string like that? Probably mean it's not a JSON Web Token, so why use this authenticator?

**Comment by knownasilya** [comment]
@jpadilla it is a jwt, just the data I put into it is a string, instead of an object. This is the most basic jwt token, without exp or anything.

**Comment by jpadilla** [comment]
Interesting. The [spec](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-4) defines the JWT Claim as:

> The JWT Claims Set represents a JSON object whose members are the claims conveyed by the JWT.

So why not just send a JSON object with just one key and your value?

**Comment by knownasilya** [comment]
@jpadilla I probably will do that eventually :+1: just wanted to fix this so it can handle this use case, since https://github.com/auth0/node-jsonwebtoken allows a string as data.

**Comment by jpadilla** [comment]
@knownasilya definitely valid, just wanted to make sure. Thanks again!

**Pull request merged**
