### PR TITLE
move ember-get-config to production dependencies

### PR DESCRIPTION
**Pull request by jakesjews**
Without this package in production dependencies I am getting errors about importing ember-get-config.

### CODE REVIEW

**Review by fenichelar — DISMISSED** [review]

**Comment by fenichelar** [comment]
@jakesjews Great! In the interest of time, would you mind incrementing the version in `package.json` and `package-lock.json` to `4.0.1`?

**Comment by jakesjews** [comment]
sure thing

**Review by fenichelar — APPROVED** [review]
Thanks!

**Comment by fenichelar** [comment]
@jpadilla I think we will want to get a new release pushed out to NPM asap - v4.0.1.

**Comment by jpadilla** [comment]
Just released v4.0.1! Thank you @jakesjews and @fenichelar

**Pull request merged**
