### PR TITLE
Add ability to override Accept header

### PR DESCRIPTION
**Pull request by thegranddesign**
Closes #171 and #159

### CODE REVIEW

**Comment by thegranddesign** [comment]
@jpadilla got a passing build :+1:  Any chance we can get this merged in? 😘

**Comment by thegranddesign** [comment]
Oh.... and released 😁 :wink:

**Comment by jpadilla** [comment]
@thegranddesign fantastic! Would you mind adding a simple test that covers this?

**Comment by thegranddesign** [comment]
I don't know how to test things in Ember :(

**Pull request merged**
