### PR TITLE
Move ember-fetch to dependency

### PR DESCRIPTION
**Pull request by abhishek97**
`ember-fetch` is a dependency. Used here: https://github.com/jpadilla/ember-simple-auth-token/blob/master/addon/authenticators/token.js#L2

### CODE REVIEW

**Comment by fenichelar** [comment]
Awesome! Could you please add the updated `package-lock.json`?

**Comment by abhishek97** [comment]
@fenichelar updated lock file, I'm using npm `6.1.0`

**Review by fenichelar — APPROVED** [review]

**Comment by fenichelar** [comment]
@jpadilla Do you want to merge this in?

**Comment by mhluska** [comment]
After upgrading to this, I started seeing the following error in FastBoot:

```
Error: Could not find module `fetch` imported from `ember-simple-auth-token/authenticators/token`
```

I'm still trying to figure out how to fix it.

**Comment by klytron** [comment]
@mhluska did you ever find a fix, seeing the same error.

**Comment by klytron** [comment]
@fenichelar I am starting a fresh emberjs project with `ember-simple-auth-token@4.0.4`. 
Thanks `ember install ember-fetch` solved it.

**Comment by mhluska** [comment]
@fenichelar I still get `Could not find module fetch imported from ember-simple-auth-token/authenticators/token` on the latest 4.0.4. I don't really want to install ember-fetch myself since that leads to other issues for me.

I think `ember-fetch` should be a peer dependency:

> For addon authors, if the addon supports Fastboot mode, ember-fetch should also be listed as a peer dependency. This is because Fastboot only invokes top-level addon's updateFastBootManifest (defail), thus ember-fetch has to be a top-level addon installed by the host app.

**Pull request merged**
