### PR TITLE
Add support for ember-fetch v7 and v8

### LINKED ISSUE #283: fetch is not defined - maybe your browser targets are not covering everything you need
I'm upgrading my applications to Ember 3.20 and I have run into this error:

`fetch is not defined - maybe your browser targets are not covering everything you need`

The root cause is the dependency to ember-fetch 6.7.2 in ember-simple-auth-token.  The fix is to force the dependency to resolve to ember-fetch 8.0.2.

```json
  "resolutions": {
    "ember-simple-auth-token/ember-fetch": "^8.0.2"
  },
```

### PR DESCRIPTION
**Pull request by fenichelar**
Fixes #283

### CODE REVIEW

**Comment by fenichelar** [comment]
v5.2.0
```
# Changelog

- Add support for `ember-fetch` v7 and v8 #283
```

**Comment by faridelnasire** [comment]
Awesome! I'd love for this to be merged in as soon as possible, I've been having some issues with fetch not being defined.

**Comment by fenichelar** [comment]
@jpadilla When you get a chance, can you please review?

**Review by jpadilla — APPROVED** [review]

**Comment by fenichelar** [comment]
@jpadilla Thanks!

**Pull request merged**
